env:
  node: true
  es6: true
  mocha: true

parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true

plugins: [ haraka ]

extends: [ eslint:recommended, plugin:haraka/recommended ]

root: true

globals:
  OK: true
  CONT: true
  DENY: true
  DENYSOFT: true
  DENYDISCONNECT: true
  DENYSOFTDISCONNECT: true
